### ISSUE TITLE
HL register goes past 0xFFFF without rolling over under PyPy

### ISSUE THREAD

**Issue by krs013** [Baekalfen/PyBoy#106]
I was testing a game called Flipull (md5 `4fcc13db8144687e6b28200387aed25c`) and it runs fine with Cython, but has an emulation error under PyPy:

```
(pypyboy) ❯ python -m pyboy roms/Flipull\ \(USA\).gb
565      INFO     Window type is: SDL2
675      INFO     SDLWindow initialization
675      INFO     Scale: x3 (480, 432)
910      INFO     Cartridge type: 0x00 - ROMOnly,
910      INFO     Cartridge size: 2 ROM banks of 16KB, None RAM banks of 8KB
Traceback (most recent call last):
  File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/pypy3/7.3.0/libexec/lib-python/3/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/__main__.py", line 113, in <module>
    main()
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/__main__.py", line 73, in main
    while not pyboy.tick():
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/pyboy.py", line 213, in tick
    self.mb.tickframe()
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/mb.py", line 169, in tickframe
    self.calculate_cycles(456)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/mb.py", line 106, in calculate_cycles
    cycles = self.cpu.tick()
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/cpu.py", line 194, in tick
    return self.fetch_and_execute(self.PC)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/cpu.py", line 178, in fetch_and_execute
    return opcodes.execute_opcode(self, opcode)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/opcodes.py", line 4804, in execute_opcode
    return LD_22(cpu)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/opcodes.py", line 327, in LD_22
    cpu.mb.setitem(cpu.HL, cpu.A)
  File "/Users/Kristian/Documents/GitHub/PyBoy/pyboy/core/mb.py", line 298, in setitem
    raise Exception("Memory access violation. Tried to write: %s" % hex(i))
Exception: Memory access violation. Tried to write: 0x10000
```

Since the address being written is `0x10000`, my guess is that the game intentionally overflows the `HL` register pair, and that PyPy doesn't roll it over to 0 automatically since it doesn't have typed variables.

**Comment by krs013** [comment]
Inserting `cpu.HL &= 0xFFFF` on line 329 of `opcodes.py` in method `LD_22` seems to fix this behavior and causes the output to match that of Cython, with the following warnings:

```
2590     WARNING  Unexpected write to 0x0000, value: 0x00
2591     WARNING  Unexpected write to 0x0001, value: 0x00
2591     WARNING  Unexpected write to 0x0002, value: 0x00
2591     WARNING  Unexpected write to 0x0003, value: 0x00
2591     WARNING  Unexpected write to 0x0004, value: 0x00
2592     WARNING  Unexpected write to 0x0005, value: 0x00
2592     WARNING  Unexpected write to 0x0006, value: 0x00
2592     WARNING  Unexpected write to 0x0007, value: 0x00
2592     WARNING  Unexpected write to 0x0008, value: 0x00
2593     WARNING  Unexpected write to 0x0009, value: 0x00
2593     WARNING  Unexpected write to 0x000a, value: 0x00
2593     WARNING  Unexpected write to 0x000b, value: 0x00
```

I don't know if this is the correct behavior for `(HL+)`, but it's better than crashing. There are a few other unchecked instances where `HL` is incremented or decremented without rollover checks. Obviously the actual fix needs to be in `generator.py`, but it's likely more than just `LD_22`. Also we may need to add tests for this, if the Blargg roms don't catch it.

**Comment by Baekalfen** [comment]
`cpu.HL &= 0xFFFF` is not the correct way to go. These are symptoms, that something else has already gone wrong, and a loop has either gone infinite or is running too long, or it's executing data as code

**Comment by Baekalfen** [comment]
But nice to map errors like this, so we can improve the emulator

**Comment by nicoeps** [comment]
Does #151 fix this issue?

**Comment by Baekalfen** [comment]
I'm not sure. Maybe @krs013 still has the game?

**Comment by krs013** [comment]
Just tested this on the prerelease branch. PyPy behavior now matches Cython and prints out the warnings shown above. So for my original intents of this issue, it is fixed, but as Baekalfen points out there may be an underlying issue that causes this overflow. I'd have to run it on a different emulator to see if that's expected behavior, or if there's an underlying bug besides it.
