### ISSUE TITLE
Animation bug in Pokemon Blue

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#113]
When Red moves to the left out of picture, the tiles are not moved synchronously and seem to gitter.

[Untitled.mov.zip](https://github.com/Baekalfen/PyBoy/files/4319592/Untitled.mov.zip)
![Untitled](https://user-images.githubusercontent.com/5528170/76443201-5b9c5a00-63c2-11ea-96cf-2f6fe254709b.png)

**Comment by krs013** [comment]
This seems to be normal (buggy) behavior for this game. I just checked it with Gambette and saw similar visual glitches.

**Comment by Baekalfen** [comment]
Wow, that's weird... But thanks for investigating!
