### ISSUE TITLE
Fixing screen rendering

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#122]
As noted by Nico on Discord:
> There seems to be a problem with sprite rendering. Sprites are not showing up in the game "Dragon Warrior Monsters". Think there was the same issue with a PPU test rom too

And from his screenshot of Wario:
![unknown](https://user-images.githubusercontent.com/5528170/80063758-e67e8180-8536-11ea-9b95-9123368bed66.png)

There are also several issues in Pokemon Pinball. The ball is showing twice (it shouldn't, right?) and there seems to be a problem with vertical flip on some of the spinning elements in the game.
We'll need to improve on the rendering pipeline to better support all games.

**Comment by nicoeps** [comment]
Only noticed now that an issue was made for this. I think the Pokemon Pinball ball behavior (the ball showing twice) is normal, as it also happens on other emulators. It is hard to see if it happens on real hardware, but I suspect it is done on purpose to make the ball look smoother while moving. The sprite missing in Wario Land is most likely a sprite priority issue, where the missing sprite is being drawn over by a sprite with lower priority. In this example the sprites have the exact same coordinates, but the brick sprite appears first in OAM and should therefore have higher priority. Funny enough, the sprites in Dragon Warrior Monsters do appear in the sprite window in debug mode, but not in the actual game window. This could possibly have something to do with sprites being disabled/enabled mid frame, but I am not sure.

**Comment by krs013** [comment]
Yeah I think pokemon pinball implementation has some kind of artificial motion blur. Some emulators implement frame smoothing/averaging to make the output look more natural for games that use effects like that. I'm not sure if that's something that would be for pyboy to do, though.

**Comment by Baekalfen** [comment]
It sounds like these issues has been solved with the newest update to the LCD code
