### ISSUE TITLE
Gym enviornment wrapper

### ISSUE THREAD

**Issue by MathisFederico** [Baekalfen/PyBoy#124]
There is no function to turn a PyBoy instance into a suitable [Gym environment](http://gym.openai.com/docs/)

So we have to build one !

We will probably use the object game_wrapper (needed to make a reasonable reward function) as super class.

We need to build the base [Gym environment](http://gym.openai.com/docs/) attributes :
- action_space
- observation_space

And methods:
- step(action) -> (next_observation, reward, done, info)
- reset() -> first_observation
- render() ->
- close() ->

There is a lot to discuss about, so feel free to do so ! (Types of observations, compatibility of render, ...)

**Comment by joaosferreira** [comment]
Hello, this looks really interesting and promising, I would like to help somehow.

I'm just getting started with Gym and this seems a good opportunity for me. If you can help me get started on this issue I would really appreciate it.

Thank you!

**Comment by Baekalfen** [comment]
We seem to have solved this in #126 and #136 :)
