### ISSUE TITLE
Tests for openai_gym.py

### ISSUE THREAD

**Issue by MathisFederico** [Baekalfen/PyBoy#129]
We need to run a game with steps and make sure that :

- steps properly make a frame step, taking into account the action and action_type (press, toggle, all).

- done is True only when the game is done (mostly dying or winning) or window is closed.
- rewards comes as expected (built by the fitness function of the wrapper).

For tests it would be nice to have a saved state at some points (for example clearing a row in tetris) to test rewards. Or last frame before dying to test done. And so on ... but I need help for that !

**Comment by Baekalfen** [comment]
I'll try to make a quick, hacked version of Tetris, which we can use. I plan to patch/hack the "next tetrimino" routine in runtime to output the ones we want. I'll make this a part of the game wrapper.

http://149.154.154.153/wiki/Tetris_(Game_Boy):ROM_map

**Comment by Baekalfen** [comment]
I've pushed my changes to #126.

**Comment by MathisFederico** [comment]
Nice I'll take a look to finish the tests

**Comment by Baekalfen** [comment]
We seem to have solved this in #126 and #136 :)
