### ISSUE TITLE
Observation types 'compressed' and 'minimal'

### ISSUE THREAD

**Issue by MathisFederico** [Baekalfen/PyBoy#137]
For some games (like tetris) it might be easier to work with a 'compressed' observation, that is mapping the background (id 47) to 0, the T block (id 133) to 1, ..., and the I block([138 139 139 143]) to 8.

Even, a 'minimal' representation with blank as 0 and anything else as 1 could be usefull.

For this, the game_wrapper needs a table (tile ID, compressed_ID, minimal_ID) for all the 384 tiles.

**Comment by Baekalfen** [comment]
Is this done?

**Comment by MathisFederico** [comment]
Yup !
