### ISSUE TITLE
Static link SDL2 for all platforms

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#138]
In the binary wheel for PyPi (`pip install pyboy`), we would like to include the necessary dependencies for SDL2, so the user doesn't need to install it manually.

**Comment by krs013** [comment]
I think it would be nice to have some way to automate this as well, but while I don't have a better solution at the moment I will mention for the record that [static linking is allowed but discouraged](https://wiki.libsdl.org/Installation#Static_linking) for "[technical and moral reasons](https://hg.libsdl.org/SDL/file/default/docs/README-dynapi.md)". But if you just mean bundling `SDL2.dll` along with the binary wheel, then that's great and I agree that we should do that.

**Comment by 201512130144** [comment]
I downloaded pyboy (pip install pyboy) and tried to deploy the sdl2 environment, but it didn’t seem to have any effect, so I haven’t started it on pycharm yet. I’m a rookie, what should I do now?

**Comment by krs013** [comment]
@201512130144 The installation instructions are [here](https://github.com/Baekalfen/PyBoy/wiki/Installation), and if you still need help after that we can talk in the installation support channel on the discord: https://discord.gg/UhByrD7

**Comment by Baekalfen** [comment]
We took another approach #220
