### ISSUE TITLE
Update game wrappers with "game over" function

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#139]
Super Mario Land and Kirby miss a function to detect if the game has ended.

In Tetris, it's defined in the `game_over` function. An equivalent function need to be implemented for the other two games.

**Comment by MathisFederico** [comment]
Done for Mario in #144 do you want me to do a separate merge request ?

**Comment by Baekalfen** [comment]
It's ok to keep it in that PR. I'll get to it asap

**Comment by MathisFederico** [comment]
Maybe there is a similar RAM value for GameOver in Kirby like in mario ?
