### ISSUE TITLE
Move testing to free test ROMs. Skip commercial games

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#140]
Our test suite heavily depends on commercial games. We need to move to use better and more accurate test ROMs, than we can include in the Travis build. This would open up for automatic testing of pull requests.

**Comment by naclander** [comment]
I would like to add to this feature request. I cloned the project expecting to build and run some tests, but apparently the tests in the `tests` directory don't run unless I populate the `ROMs` folder?

I would be great if unit tests could be run from a clean clone of the project. This can also be documented in the [wiki](https://github.com/Baekalfen/PyBoy/wiki/Installation).

**Comment by Baekalfen** [comment]
In the newest version of `prerelease` (v.1.1.0), it will now skip any test, which it cannot find ROMs for. The coverage will be worse, but it won't crash.

**Comment by naclander** [comment]
Just tested this out and it seems to mostly work. However, `test_external_api.py::test_screen_buffer_and_image` fails when using the default ROM as the `any_rom`.  It passes when the Tetris ROM is the `any_rom`. 

From my understanding this test looks for the specific boot logo which comes from the proprietary ROMs, so it makes sense this would fail for any non-Nintendo ROMs ( like the default rom ). 

I think the skip logic needs to be a little stricter here. I wasn't sure if I should create a new issue for this particular bug.
