### ISSUE TITLE
Fix build problems on Windows Python 3.8

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#149]
Currently, it's not possible to run PyBoy on Windows with Python 3.8, as it cannot load/find SDL2.dll.

It might be the same issue as here: https://github.com/marcusva/py-sdl2/issues/145

**Comment by krs013** [comment]
Has this has been fixed with some Windows or Python update since the issue was opened? I am now able to compile and install PyBoy from source on Python 3.8.5 and it runs just fine. Would the precompiled binaries work too?

**Comment by Baekalfen** [comment]
It might actually have been fixed. But our automatic testing is blocked by some issues with SciPy. We are getting an error about "No lapack/blas resources found".

**Comment by krs013** [comment]
Is there a way I could try that out? When I run the tests on my Windows machine they seem to work fine (except for OpenGL but I need to get freeGLUT for that). Am I missing something, or is this for PyPy, or is this only for the environment on Travis or something?

**Comment by Baekalfen** [comment]
It's the install of SciPy that fails. I think you can try it out by just opening a PR and change the `.travis.yml` file.

**Comment by Baekalfen** [comment]
The original issue seems to have been fixed
