### ISSUE TITLE
Propagate log level to all files

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#152]
The current `log_level` function in `logger.py` doesn't seem to propagate its setting. At least not in Cython

**Comment by velvetkeyboard** [comment]
Do you mean the following?
```
import logging

logging.basicConfig(level=LOGLEVEL)
```

**Comment by Baekalfen** [comment]
You can have a look at what we have https://github.com/Baekalfen/PyBoy/blob/master/pyboy/logger.py

Only thing I know, is that it's not working

**Comment by velvetkeyboard** [comment]
@Baekalfen Sounds like the current implementation is misusing the logging instances. I will try make a proposal in a week.
