### ISSUE TITLE
Change readme instructions about pypy

### ISSUE THREAD

**Issue by Yardanico** [Baekalfen/PyBoy#16]
PyPy in ubuntu package repository is very old (5.1.2+dfsg-1~16.04 in xenial updates, and latest version is 5.6.0)
It's better to use Portable pypy binaries: https://github.com/squeaky-pl/portable-pypy  they can run almost on any linux distribution (including ubuntu) and does not depend on system libs)

**Comment by Baekalfen** [comment]
Thanks for the heads-up. I'm not a regular Ubuntu user myself.

Would you like to correct it and make a pull-request? Otherwise I'll take a look at it.

**Comment by TiberiumPY** [comment]
@Baekalfen english isn't my first language, but it will not that hard:
download pypy from https://github.com/squeaky-pl/portable-pypy  (and choose needed architecture)
extract it in any folder (better to have in home directory, like /home/tiberium/pypy)
Add /home/tiberium/oypy and /home/tiberium/pypy/bin to PATH
And then all your instructions.

**Comment by TiberiumPY** [comment]
@Baekalfen by the way, there's already game boy emulator written in RPython (Restricted Python). PyPy is also written in RPython, so this emulator can be translated to C

**Comment by Baekalfen** [comment]
Ok, but thanks anyway. I'll rewrite the Ubuntu/Linux instructions.

I have seen it before, but it seemed abandoned.. And we wanted to create our own emulator for the learning experience.

**Comment by TiberiumPY** [comment]
@Baekalfen althrought it's abadoned, it fully functional
