### ISSUE TITLE
Handle tile_map changes in game

### ISSUE THREAD

**Issue by MathisFederico** [Baekalfen/PyBoy#163]
We need a way to modify the tiles_compressed and tiles_minimal used when the tiles_map is change by the game (like world 2 in SuperMarioLand).

I need help to detect when the tile map is changed by the game !

**Comment by krs013** [comment]
I assume this only needs to be updated on a frame-by-frame basis, right? A "tile map dirty" flag of sorts shouldn't be hard to add. Then you could just check it in `post_tick()` or something and update `tiles_*`, right?

**Comment by MathisFederico** [comment]
Something like that I guess ^^
I need to know 'the tiles map ID' at every frame

**Comment by Baekalfen** [comment]
I think it's something we need to patch on a game-to-game basis. It's hard/impossible to auto-detect reliably.

But another thing is, Super Mario Land is very lazily/cleverly programmed, so the IDs actually don't change meaning. The IDs of monsters in 1-1 are still monsters in 2-1:

[Untitled.mov.zip](https://github.com/Baekalfen/PyBoy/files/4598494/Untitled.mov.zip)

But the AI will have to take into account, that monsters act differently in world 1-1 than 2-1.

**Comment by MathisFederico** [comment]
Well not entirely, altough monsters are the same IDs, neutral blocks and empty blocks are not, for example in world (2, 3) neutral blocks are not detected by tiles_minimal nor tiles_compressed

**Comment by Baekalfen** [comment]
Could you point out which ones?

**Comment by MathisFederico** [comment]
Well i still didn't manage to run the debug in world 2-3 ^^', but if you run in tiles_compressed or tiles_minimal modes you will see that walls are not detected

**Comment by Baekalfen** [comment]
Closed for inactivity. And as I can see, it's not an issue in Super Mario Land
