### ISSUE TITLE
Linking problem on Ubuntu_python 3.7

### ISSUE THREAD

**Issue by TurtleParade** [Baekalfen/PyBoy#166]
An error occured in Python 3.7 version that the Pyboy module could not be imported.
while pyboy installed, following below source codes
- sudo apt install libsdl2-dev
- sudo apt update
- sudo apt install python3 python3-pip python3-dev libsdl2-dev build-essential
- python3 -m pip install --upgrade pip
- python3 -m pip install pyboy

successfully installed, but python couldn't import 'pyboy module' repeatedly

then after downgrading python version from 3.7 to 3.6, finally solved the problem

wondering if there is any solution using python 3.7

**Comment by Baekalfen** [comment]
Could you show us the error message? It doesn't sound like something we have seen before

**Comment by TurtleParade** [comment]
At Ubuntu terminal:
- python3 -m pip install --upgrade pip
- python3 -m pip install pyboy

Installation does not proceed with the above two codes, with `No module named pip` error message

At python IDLE:
`ModuleNotFoundError: No module named 'pyboy'`

with the above message, PyBoy cannot be executed

**Comment by Baekalfen** [comment]
I think you're running multiple installations of Python at the same time

**Comment by TurtleParade** [comment]
It was solved by reinstalling Python from another computer.
Thank you for your reply.
