### ISSUE TITLE
Arrangement files_running problem

### ISSUE THREAD

**Issue by TurtleParade** [Baekalfen/PyBoy#167]
finished installing python and game files, then ran GameBoy on python following below codes but failed
- from pyboy import PyBoy
- pyboy = PyBoy('Super Mario Land.gb')
- while not pyboy.tick()
- pass

on Python shell:
FileNotFoundError : ROM file Super Mario Land.gb was not found!

then shifted all files including Game Boy ROM(.gb) and .py files to the same directory
and worked well

Is there any way to run game if the files are in different directories?

**Comment by Baekalfen** [comment]
You just have to provide the path for the ROM file as first argument: `PyBoy('path/to/rom/Super Mario Land.gb')`
