### ISSUE TITLE
Can't run Pokemon Red...

### ISSUE THREAD

**Issue by arthur-fontaine** [Baekalfen/PyBoy#189]
I try to run Pokemon Red, but when I arrive in the screen to create a game, it says:
```
1771008  pyboy                          ERROR    Unexpected write to 0x6000, value: 0x01
1771009  pyboy                          ERROR    Unexpected write to 0x6000, value: 0x00
```
I don't know why, and how to resolve it...
~~[My ROM]()~~ [REMOVED]
If you could help me...

**Comment by Baekalfen** [comment]
Does the game work fine otherwise? I don't remember the exact addresses, but it might just be a bug in the game, that doesn't affect anything https://github.com/pret/pokered/issues/155

**Comment by Baekalfen** [comment]
Also, please don't post ROMs here, as it's copyrighted contents, and could be used to take down the project.

**Comment by arthur-fontaine** [comment]
oh sorry I didn't know... The ROM works fine on Retroarch, so it is not a ROM bug I suppose...

**Comment by Baekalfen** [comment]
Does PyBoy crash or does it continue to function? I don't have Pokemon Red, but Blue makes the same warnings and it's a bug in the ROM, and other emulators just ignore it, as it's harmless.

**Comment by arthur-fontaine** [comment]
And there is no way to make the ROM works with PyBoy?

**Comment by Baekalfen** [comment]
Could you verify that your ROM file has the same sha1 checksum as these? https://github.com/pret/pokered

**Comment by Baekalfen** [comment]
Again, does PyBoy crash or stop when you see this, or does it continue anyway?

**Comment by arthur-fontaine** [comment]
> Could you verify that your ROM file has the same sha1 checksum as these? https://github.com/pret/pokered
 
With the "global" ROM, the sha1 checksum of my ROM is the same. With it, I can go until the screen where Sacha is with many Pokemon.
With the Fr ROM, the sha1 checksum is `47a7622fa30e6402a3891fe65b3a930bf9bd7aec`. With it, I can go until the screen with a little box at the top-right where it's written "NEW GAME".

 > Again, does PyBoy crash or stop when you see this, or does it continue anyway?

uh sorry I didn't pay attention to the question...
I think not because I can still use `pyboy.stop()`. So it doesn't crash.

**Comment by Baekalfen** [comment]
I don't see this on my `debugger` branch, so let's wait until that is merged, and we can revisit this issue
