### ISSUE TITLE
Fullscreen option

### ISSUE THREAD

**Issue by emma-makes** [Baekalfen/PyBoy#221]
I'm working on a bot that plays games on its own and have that running 24/7. It would be fantastic if there was an option to run the game in fullscreen mode.

I've looked through the options, but haven't come across something like that.

**Comment by Baekalfen** [comment]
There's currently no way of doing it, but it's likely a very easy fix.

I'll see if someone wants to take a swing at it. Otherwise, I'll see if I get time to do it soon.

**Comment by Baekalfen** [comment]
@emma-makes This is fixed in the #193 PR. Hopefully it gets merged soon.
