### ISSUE TITLE
Pokemon Pinball: In CGB, it uses the wrong palette colors on the menu screen

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#224]
![8F92C113-BD56-4441-93E8-47353816B6F0](https://user-images.githubusercontent.com/5528170/174887572-e8279556-8a3a-49c6-b044-2486857243cd.jpg)

**Comment by NicoleFaye** [comment]
Just to add a little more detail to this issue. The initial load of the red stage color pallet, before a point of view transition has the same issue as the title screen.

|Pyboy|mGBA|
|---|---|
|![image](https://github.com/Baekalfen/PyBoy/assets/41876584/6036e55e-5874-4e43-87bd-d75449e709a7)|![image](https://github.com/Baekalfen/PyBoy/assets/41876584/ce93c1c1-4c6f-4787-aab0-43d448636488)|
|![image](https://github.com/Baekalfen/PyBoy/assets/41876584/d3b43355-9eba-4a09-a765-30b04a1fbe74)|![image](https://github.com/Baekalfen/PyBoy/assets/41876584/3580c132-1d72-4420-a6c1-80142d2d1fae)|
