### ISSUE TITLE
requirements.txt installs Cython only on CPython, but setup.py tries to use it on anything that is not PyPy

### ISSUE THREAD

**Issue by timfel** [Baekalfen/PyBoy#235]
The requirements txt leads to Cython not being installed on e.g. GraalPy, but then setup.py tries to Cythonize, because GraalPy is not PyPy
https://github.com/Baekalfen/PyBoy/blob/311562aa5737771c0702ec78f6639d1b04f6a0c0/setup.py#L19
https://github.com/Baekalfen/PyBoy/blob/311562aa5737771c0702ec78f6639d1b04f6a0c0/setup.py#L35

**Comment by Baekalfen** [comment]
Thanks for pointing this out. Would you want to use Cython with GraalPy?

**Comment by timfel** [comment]
Preferably not, we have a similar C API emulation layer as PyPy and like PyPy it is generally better for us to JIT the Python code instead of trying to emulate CPython's API.

**Comment by Baekalfen** [comment]
Understood. If it's simply changing those two statements, could you make a PR of how it works for you? I don't have a lot of spare time to test it out with GraalPy myself.

**Comment by timfel** [comment]
Thank you!
