### ISSUE TITLE
Savestates not loading with CGB games

### ISSUE THREAD

**Issue by DeCoded-Void** [Baekalfen/PyBoy#245]
Upon loading a state it will cause the CPU to halt. Using a DMG bootrom and `pyboy.PyBoy.cgb=False` will no longer cause it to hang but it will continue to leave a warning without loading in the state, even if the state is saved in CGB mode:

`CRITICAL:pyboy.core.mb:Loading state which is not CGB, but PyBoy is loaded in CGB mode!`

**Comment by Baekalfen** [comment]
What version are you running? Because I fixed an issue like this in v1.5.5

**Comment by Baekalfen** [comment]
Ok, I see the issue. I'll be deploying a fix shortly

**Comment by Baekalfen** [comment]
I'm now deploying v1.5.6 that should fix this. I will mark the issue as closed, but you're welcome to re-open it, if it didn't fix it.
