### ISSUE TITLE
Kirby's Dream Land: Plugin bug

### ISSUE THREAD

**Issue by eugeneyjy** [Baekalfen/PyBoy#261]
I noticed some bug when using the `game_wrapper()` of Kirby's Dream Land.
1) The `GameWrapperKirbyDreamLand().score` doesn't calculate score correctly. The digits are calculated in reverse to their location in memory.
2) The `GameWrapperKirbyDreamLand().game_over()` should return true if `lives_left==0`, not `health==0`. Not sure if this is intended but this cause problem when trying to use the `game_over()` function to decide the terminated state in custom [`gymnasium.Env.step()`](https://gymnasium.farama.org/api/env/#gymnasium.Env.step).

May I make a pull request regarding to the bugs?

![image](https://github.com/Baekalfen/PyBoy/assets/46506744/e834fb11-1e52-4d7c-965b-e2435051f245)

**Comment by Baekalfen** [comment]
Yes, that looks reversed. You're welcome to submit a PR with a fix

**Comment by Baekalfen** [comment]
Fixed in #263
