### ISSUE TITLE
Pokemon Gold: Animation for Harden

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#30]
[harden.mov.zip](https://github.com/Baekalfen/PyBoy/files/1199762/harden.mov.zip)

**Comment by Baekalfen** [comment]
Exactly the same error occurs for Growl

**Comment by krs013** [comment]
This does not happen with the Scanline GameWindow.

**Comment by krs013** [comment]
[Bernoulli Screen Shot 2019-03-08.zip](https://github.com/Baekalfen/PyBoy/files/2945473/Bernoulli.Screen.Shot.2019-03-08.zip)

**Comment by krs013** [comment]
Actually, that bug doesn't seem to be present in the SDL2 GameWindow either, although the animations are different.

**Comment by krs013** [comment]
[Harden SDL2 Animation.zip](https://github.com/Baekalfen/PyBoy/files/2947954/Harden.SDL2.Animation.zip)

**Comment by Baekalfen** [comment]
It does look like the bug is gone. The different animations, seems to be because my implementation doesn't update the color palette correctly. Although it seems, it should be updated between frames.

**Comment by krs013** [comment]
Is there any reason to keep this open? There are still some animation bugs that need addressing (try Donkey Kong Land) but unless we want to expand this into an umbrella issue for all render bugs I think we can close it.

**Comment by Baekalfen** [comment]
I'll just close it. If you find any bugs or glitches, then do tell me, so we can make PyBoy even better :)
