### ISSUE TITLE
PyBoy not rendering on remote host over VNC connection

### ISSUE THREAD

**Issue by martin-cala1** [Baekalfen/PyBoy#307]
Hi, 

I am able to run Pyboy locally on my MacOS without a problem. I have a cloud ubuntu server with GPUs I want to do some training on, and I connect to to it over a RealVNC connection.  When I run pyboy within the session, the graphics do not render and all I see is a black screen. How can I enable the graphics to render on the remote host?

**Comment by Baekalfen** [comment]
Hi, you should come and post it on Discord. I think there are some people that are better at helping you than me: https://discord.gg/Zrf2nyH
