### ISSUE TITLE
input not working

### ISSUE THREAD

**Issue by FunnyIvri** [Baekalfen/PyBoy#308]
for some reason input isnt working
heres my code:

```
from pyboy import PyBoy, WindowEvent

gameBoy = PyBoy('test.gb')
gameBoy.set_emulation_speed(1)
while True:
    gameBoy.tick()
    gameBoy.send_input(WindowEvent.PRESS_BUTTON_START)
    gameBoy.tick()```

**Comment by Baekalfen** [comment]
You probably need to release the button too: `gameBoy.send_input(WindowEvent.RELEASE_BUTTON_START)`

**Comment by FunnyIvri** [comment]
this didnt work :(

> You probably need to release the button too: `gameBoy.send_input(WindowEvent.RELEASE_BUTTON_START)`

**Comment by Baekalfen** [comment]
Your game might not read the input every frame. Try adding 5 calls to tick between each input.

Otherwise, come and get help on the Discord server. I try to keep the issues here on GitHub about bugs in PyBoy, rather than troubleshooting https://discord.gg/Zrf2nyH

**Comment by FunnyIvri** [comment]
thanks this worked!
could have never guessed that was the issue!
