### ISSUE TITLE
Is it possible to add custom keybindings

### ISSUE THREAD

**Issue by iimog** [Baekalfen/PyBoy#339]
I wrote some code to automatically play Tetris using the game wrapper. I would like to toggle between the automatic play and manual play (e.g. to navigate menus and to see how the algorithm handles certain situations). I saw Phwiddy use a text file `agent_enabled.txt` [here](https://github.com/PWhiddy/PokemonRedExperiments) to toggle between those modes. I think it would be much more convenient to add a custom keybinding to toggle. Is there any way to achieve this right now with pyboy (and sdl2)?
Probably related to #249 

Thank you for this awesome tool and in advance for any help!

**Comment by Baekalfen** [comment]
This seems more like a discussion of a specific solution, rather than an issue with PyBoy. Discord is much better suited for this https://discord.gg/Zrf2nyH
