### ISSUE TITLE
Add option to disable keybindings when running with display modes

### ISSUE THREAD

**Issue by AoifeHughes** [Baekalfen/PyBoy#340]
Similar to #339 and #249 

Im currently doing some debugging and it's very annoying to have the keybindings affecting the game state when I don't want them to! It would be great to have a simple way to have an SDL or OpenGL window but with the inputs disabled.

**Comment by Baekalfen** [comment]
What would be the point of not allowing inputs from the API? Then the emulator can't do anything?

**Comment by Baekalfen** [comment]
Sounds like a too specific use-case to have built-in. You can come and join the Discord server if you want to discuss solutions.

**Comment by Baekalfen** [comment]
I'm offering you to come to Discord if you want any further help. I can't help everyone 1:1 on here.

Also, others on Discord have used the API to implement more or less what you're asking for.
