### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#41]
Python 2.7 will inevitably be discontinued.

**Comment by Baekalfen** [comment]
@stillinbeta has made a bit of progress, but it seems to have stalled, waiting for NumPy support: #55

**Comment by krs013** [comment]
Based on what I've seen so far (and I may have missed something), NumPy is only needed for `shmarray.py` which in turn is needed for the (unfinished?) multiprocessing version of the GameWindow and for the `pixels2d` access in the current `GameWindow_SDL2.py`. I am trying to avoid using NumPy in my GameWindow (although it is obviously tempting), and if it works, it may be possible to remove NumPy from the project dependencies entirely. Is that right, or is it needed somewhere else?

**Comment by Baekalfen** [comment]
That sounds about right. It would be great to get rid of NumPy, as PyPy adds a high penalty to accessing NumPy arrays, compared to native lists.

I cannot remember anywhere else but SDL2, where it is required. And if we break the multiprocess version, then that is fine.

**Comment by Baekalfen** [comment]
Fixed on cython branch
