### ISSUE TITLE
Ability to compute frames as fast as possible

### ISSUE THREAD

**Issue by DaniGuardiola** [Baekalfen/PyBoy#43]
Me and @Fieoner are working on a bot and we are using your (awesome) emulator in headless mode to make it work. However, the frames are limited so that it runs in real time, which makes sense for direct standard use. For computing frames, however, it makes more sense to run it as fast as possible, so we would like to know if there's any option to make this happen or if it can be implemented.

We are happy to help.

Thanks in advance!

**Comment by Baekalfen** [comment]
Thanks for your interest in the project!

Are you using `DummyGameWindow` to make it run headless? That should disable the frame limiter, and also skip the heavy part of the screen rendering. But you will end up without a screen buffer. Instead, you can access the tile views and sprites directly, which is a lot faster. I can try to make some wrappers and documentation to make it easier to use, if you would like.

**Comment by Baekalfen** [comment]
I just noticed, I did actually implement some small wrappers called TileView and Sprite. I can extend them, if they lack any functionality.

https://github.com/Baekalfen/PyBoy/blob/master/Source/PyBoy/BotSupport/

**Comment by DaniGuardiola** [comment]
Hey thanks for the quick response! Two things:

- I just realized that we haven't yet tried the headless mode. We are still on early stages of the project and we are using the standard window in order to see what's going on, sorry about that :sweat_smile:

- We are indeed using the screen buffer to get the pixel matrix and then rendering it into an image. We haven't looked yet into how to render the screen from the tileviews and the sprites, although we did notice a mention to it in the documentation. At some point I personally plan to read the report and try to understand the whole PyBoy codebase, just out of curiosity, but for now I wonder if it would be possible to render the screen selectively only on the frames that we want, even on headless mode, to obtain the pixel matrix, in the same way the standard window mode currently does. Would this make sense?

Thank you :)

**Comment by krs013** [comment]
With the new Cython version, is there anything else to do here? The dummy window runs under Cython at roughly 200x real time.

OTOH, it still may be worthwhile to have the ability to render the display to a buffer without showing it on screen, which could be a cause to keep this issue open.

**Comment by Baekalfen** [comment]
PyBoy can now be run in `headless` mode, which should provided the needed functionality to close this issue.
