### ISSUE TITLE
FrameRate Very Low.

### ISSUE THREAD

**Issue by oxenoxeno** [Baekalfen/PyBoy#47]
It is hardly control in SDL2 in playing Super_Mario_Land.gb

**Comment by oxenoxeno** [comment]
Mac OS Mojave

**Comment by oxenoxeno** [comment]
5220     INFO     Cartridge type: 0x01 - MBC1, 
5220     INFO     Cartridge size: 4 ROM banks of 16KB, None RAM banks of 8KB
5220     INFO     Loading RAM is not supported on 1
5539     WARNING  Game tries to set value 0x00 at RAM address 0xbfff, but RAM banks are not initialized. Initializing 1 RAM banks as precaution

Does above problem cause the speed of the game so slow?

**Comment by Baekalfen** [comment]
Are you using PyPy?

**Comment by oxenoxeno** [comment]
> Are you using PyPy?

No, I run it directly python2.7.15;

**Comment by Baekalfen** [comment]
That is the reason. CPython is not fast enough. The instructions in the readme should show you how to get it running.
