### ISSUE TITLE
sendInput([WindowEvent.LoadState]) does nothing

### ISSUE THREAD

**Issue by ccokee** [Baekalfen/PyBoy#50]
Hi, im trying to make an IA for Motocross Maniacs but I need to load state in order to dont spend hours between bootrom loadings and such, also the rom crashes if the game timesup or loses the race so I need this to work as I intend. I was modifying tetris_bot.py in order to see if I can load rom states but it seems either this isn't implemented or I'm not using the correct method.

Im trying pyboy.sendInput([WindowEvent.LoadState]) but this does nothing.

**Comment by ccokee** [comment]
I found I can do it with the pyboy.mb.loadState method.

**Comment by Baekalfen** [comment]
That's the one. I'll make an issue, that it should be added to the exposed script/bot methods, as I can see it's a very practical feature.
