### ISSUE TITLE
About TileViews

### ISSUE THREAD

**Issue by ccokee** [Baekalfen/PyBoy#52]
First, thanks for answering me before. Now, this is more a doubt than an issue... When I use the tileview I get two windows, one for the "current map without the player" and other for the HUD (the remaining time bar, power, and such). At the moment I can retreive the "on screen" sprites but I cant get the sprites in the tileviews and I need to get the sprites near the racer (in the tileview but not on screen). How should I proceed?
This is what I see:
https://i.imgur.com/3yrvuSg.png

**Comment by Baekalfen** [comment]
No worries, I'm glad someone gets some use out of my code :)

If I understand you correctly, you are looking for the type of tiles in the background? Maybe you already know, but tiles are small static "images" of 8x8 pixels, which are placed side-by-side in the background and on the HUD. Sprites on the other hand, can be placed anywhere, and supports transparency — the player is a sprite, as it moves freely. Just to clear any confusion. Sprites are in the view with the blue stripes, and tiles are in the lower window on your screenshot.

I can see that you got the coordinates for the screen and the sprites. From those, you can find the coordinates to look up in the tileviews with `getTileView(high)`. If you set `high` to true or false, you can switch between the background and HUD.

Remember, that the tileview you get back, contains the indices of the tiles (the corresponding tile is in your lowest window). The tileview is not the framebuffer with pixels in it. You should be able to use `get_tile(x, y)` to find the tile at the coordinate you provide. `x` and `y` go from 0 to 31, as they are the index of a tile, and not the pixel on the screen — you can simply divide the screen pos by 32 to find the tile index.

PS.
You can get the framebuffers for the tileviews through the GameWindow instance, but I don't recommend it, as it only works with SDL, and it might break if I change the code.

Hope this helps :)

**Comment by ccokee** [comment]
The thing is Im trying to get what I have inmediately under the player and I get nonsense :S

**Comment by Baekalfen** [comment]
Have a look at the readme now, I've tried to add a way to determine the indices on screen. Granted, it would be easier to use a tool in the GUI, but this is what I can produce with a short notice.

You're correct, it should be divided by 8!

**Comment by Baekalfen** [comment]
That sounds right. As you can see in the tileview on the screenshot, the ground of the player stops at the bottom of the tileview. But on the screen there are two more tiles for the HUD ((128+144)/8 = 34 tiles).

When the screen position overflows the bound of the screen, they simply wrap around to the other side. Meaning; behind the HUD on the screen, are actually rendered to top 2 rows of the left-most tileview, you just cannot see it, as the HUD masks it.

Have a look at page 21 of the report. Figure 22 illustrates exactly this.

**Comment by Baekalfen** [comment]
Closed because of inactivity.
