### ISSUE TITLE
Improve TileView support by automatically isolating what is on the screen.

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#53]

**Comment by krs013** [comment]
This will have to wait until a TileView/debug interface is re-implemented.

**Comment by Baekalfen** [comment]
In reference to #52

**Comment by Baekalfen** [comment]
Think about how to handle scanline parameters changing

**Comment by krs013** [comment]
How does this differ from the current features of the debug windows? Is there more to do?

**Comment by Baekalfen** [comment]
TileView is a botsupport object, which should make it easier to figure out what is on the screen

**Comment by krs013** [comment]
Oh right this is for the API not the debug window, that makes sense.

**Comment by Baekalfen** [comment]
It's implemented on the `plugin_refactor` branch
