### ISSUE TITLE
Lazy imports for optional features (and faster starts)

### ISSUE THREAD

**Issue by krs013** [Baekalfen/PyBoy#58]
Since some packages (OpenGL, imageio) are only needed for certain features like video recording and experimental GameWindows, it would be nice if we could lazily import either those packages or the modules that import them. That way, someone could try the code without having to install all the dependencies (e.g., my brother had a hard time trying the code because `gcc` fails to compile Pillow on macOS). It would also speed up the startup, since there would be less work to do before the game can launch.

One place this is a problem is the GameWindows. Since `GameWindow/__init__.py` imports all of the GameWindows to its namespace, the references to that package in `main.py` trigger the imports even though it's trying to import just one of the GameWindows. While having an empty `__init__.py` and importing from the submodules would fix that, I think it would fragment the code too much (and already it's a bit interdependent that `main.py` has to check the names of the GameWindows instead of keeping that functionality in the module). So, I thought I'd open this up as an issue to see if there were any ideas about how to handle this in general and whether it's something to pursue yet.

**Comment by Baekalfen** [comment]
I agree.

For the selection of `GameWindow` in `main.py`, that is also something that bothered me. If I remember correctly, it was because of each component had to have references all around. For example both the `GameWindow` and `Interaction` needed access to the underlying window manager. I'm not sure, if this issue still exist.

**Comment by Baekalfen** [comment]
I've added a bit of lazy import to the `GameWindow`s. Now, you can run `SDL2` without having the dependencies for `OpenGL`. f4d43a92305003cb16784855c4dd92597b82d159

**Comment by krs013** [comment]
Thanks, that looks good. It does solve the OpenGL problem, though startup could still be faster. I can also take a look at it, but I'll be a bit busy for the next couple weeks so it might not be too quick.

**Comment by Baekalfen** [comment]
I'm not sure what you mean with the start-up time. Mine is almost instant. Do you mean the JIT warm-up? That is likely not affected much by imports.

**Comment by krs013** [comment]
Hmm, ok, I think you're right about the JIT part; Pypy leaves `.pyo` cached files around that help, and the first time I run things it's noticeably slower while it compiles and faster thereafter.

However, there is a small effect just because importing any module takes time in Python. On my machine, it takes about 1000 ms (assuming that's what the log prints) to get to `Boot-ROM file provided` with the current code for a scanline window. However, if I only import the GameWindow that I'm using (I deleted most of the contents of `GameWindow/__init__.py` and just reached directly into the submodules in `main.py`), then that log message prints at less than 600 ms. It's a small difference, though, and that approach at least is worse for decoupling so I don't really like it. 

If you want to address the overly tight coupling between `main.py` and the GameWindows, we can keep this open, otherwise I'd say we might as well close this for now because I can't get it to work nicely to import efficiently and still be clean. You did fix the main issue, which was that nothing worked if OpenGL wasn't present.

**Comment by Baekalfen** [comment]
Even with the `.pyo` files, there is a quite long warm-up period every time `pypy` is started. I sometimes disable the framelimiter to warm it up quicker. We could look at making some warm-up code, if needed.

With loading times measured in ms, I wouldn't bother with it. If it had an effect of the performance after loading, it would be more interesting.

I think I'll go and make `ScreenRecorder` use `imageio` as an optional import. So it gracefully outputs some warnings, if its dependencies are not met. That would close this issue.

The coupling of `main.py` and `GameWindow` seems to be a different from this issue.
