### ISSUE TITLE
Better detection of compiled/interpreted/JIT backend

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#67]
The SDL2 `Window` doesn't work in CPython without Cython, as we cannot differentiate it from the Cython version.

**Comment by krs013** [comment]
As I mentioned in the PR, I managed to fit all code for Cython/CPython/PyPy in one `.py` file and one `.pxd` file. It's not the cleanest solution, as the shadow code that does the job of the `.pxd`'s inline functions has to be hidden from Cython in an `exec()` block, but it works perfectly and is fairly readable (though you lose syntax highlighting in the `exec()` block).
