### ISSUE TITLE
BotSupport: Memory scanner

### ISSUE THREAD

**Issue by Baekalfen** [Baekalfen/PyBoy#72]
A Cheat Engine-like memory scanner to pinpoint the memory address of the score, time remaining, etc.

The features could include, but need not be limited to:

 * Search for exact value
 * Convert to and from "Binary-coded decimal" (BCD) values
 * Search for any value that increased/decreased since last search

**Comment by NicoleFaye** [comment]
I think this can be closed.

**Comment by Baekalfen** [comment]
You're right, thanks!
