### ISSUE TITLE
[Question] Can this run on a CircuitPython board?

### ISSUE THREAD

**Issue by AsherGomez** [Baekalfen/PyBoy#74]
Hey, Can this run on a CircuitPython board?

**Comment by krs013** [comment]
No, I’m afraid not. 

1) PyBoy runs on either CPython (the normal PC version of Python) with an extension called Cython, which is not compatible with CircuitPython, or PyPy, which is another PC-specific Python interpreter. It also makes use of a library called SDL for graphics that afaik is not on any board that is not at least running Linux. 

2) The CircuitPython boards I see online are nowhere close to powerful enough to run this particular game boy emulator. 

It’s possible that this could run on something like a Raspberry Pi, but we haven’t gotten around to testing or supporting that yet. Alternatively, there may be emulators written in C or C++ that could work for a microcontroller board like those that run CircuitPython, but unless someone has specifically targeted it, you’d either be looking at some medium advanced adaption work, or you’d have to write decent parts of it from scratch.

**Comment by AsherGomez** [comment]
Thanks.
