### ISSUE TITLE
Improving OPCode performance

### ISSUE THREAD

**Issue by mrAllWeather** [Baekalfen/PyBoy#75]
Currently opcodes are retrieved via a series of if statements, meaning a blind avg of 256 comparisons before the correct code is found. Swapping to an array of function pointers reduces this to a single check. 

Performance Testing
As an experiment I unified opcode function params to (cpu, v) and placed all functions in a list for lookup in the generated opcodes.py. Timing package used was yappi logging in debug mode on a windows 10 machine.

opcodes.execute_opcode

|     |Prechange (888380 calls)|Time per million|Postchanges (1102916 calls )|Time per million|Difference %
|-----|------------------------|----------------|---------------------------|----------------|------------
ttot:|9.796875|11.02779778923434|8.781250|7.055161045809472|36%
tsub:|5.531250|6.226220761385893|3.109375|2.819231020313424|54.7%

As this is a generated file the correct fix will require updating generator.py to correctly format calls into value order.

**Comment by Baekalfen** [comment]
Interesting. Did you use Cython? Cython seems to interpret the chained `if`s as a switch-case, and possibly optimize for it.

**Comment by mrAllWeather** [comment]
Hmm, I didn't set up specifically for Cython (system used was anaconda, pip installed the requirements which included cython). As I haven't used Cython previously it's likely I missed a flag or something. 

Will investigate and report back.

**Comment by Baekalfen** [comment]
That sounds really cool about the cluster. What do you intend to use it for?

**Comment by mrAllWeather** [comment]
I'm currently aiming use it to learn evolutionary AI training. Since the
gameboy has limited input and many of the games were constrained due to the
hardware it represents a great set of challenges to practice on. Initially
I'm thinking something like a mario island AI to start but moving into
things like pokemon battle AI since there are many different randomisers
available to vary the problem set.
Your emulator should be perfect for training since every core can run
headless and make use of a set of shared start states (also being python is
nice since I don't need to write a system connection like I was previously
intending to do).

**Comment by Baekalfen** [comment]
That would be really awesome. Please tell me, if you need any help interfacing with PyBoy, or reading out some information from the game.

And do give Cython a try. It will speed up the emulation by at least an order of magnitude.

I've just created a Discord server. Come have a chat if you'd like. https://discord.gg/Zrf2nyH

**Comment by mrAllWeather** [comment]
Thanks, have done :)

I'm going to try to get it working with Jupyter so I can properly document
my investigation as I go. Once I have something useful to post I'll pop it
into the discord
