### ISSUE TITLE
Replacement Boot ROM fails to start Pokemon Gold

### ISSUE THREAD

**Issue by krs013** [Baekalfen/PyBoy#89]
When using the fallback boot ROM with Pokemon Gold, the game doesn't seem to load at all, as the screen stays completely blank and the usual MBC warnings don't print out after the usual amount of time.

In case this can't be easily fixed, possible mitigations include adding an extra warning to the existing message that is printed when using the fallback boot ROM and adding the fallback ROM to the test suite.

Otherwise, we might be able to find out what is trapping execution for the game and fix this behavior. It may just be that GBC games require an extra step of authentication or palette/clock initialization before they can run.

**Comment by krs013** [comment]
NB: It was also pointed out on Discord that the fallback BIOS causes a segfault with Pokemon Gold on windows under minGW, but I haven't been able to reproduce this yet.

**Comment by Baekalfen** [comment]
The way to solve this, is to find the exact state the original boot ROM leaves the Game Boy in, and make the replacement ROM to reconstruct the same state. There are a lot of things, that the replacement currently doesn't touch.

**Comment by Baekalfen** [comment]
It would be awesome, if we could get the replacement to show a PyBoy logo on boot ;)
